version: '2'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
      - "9090:9090"
    depends_on:
      - app
  app:
    build: .
    command: sbt runSingle
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "8888:8888"
